<?php

namespace AppBundle\Repository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends \Doctrine\ORM\EntityRepository
{

    public function findPerson () {
        $pro = $this->getEntityManager()->getRepository("AppBundle:Person")->find(2);
        if ($pro) {
            return $pro;
        } else {
            throw $this->createNotFoundException('No product found for id 2');
        }
    }

    public function findPersonByName ($name) {
        $repository = $this->getEntityManager()->getRepository("AppBundle:Person");
        $query = $repository->createQueryBuilder("p")
            ->where("p.name = :name")
            ->setParameter("name",$name)
            ->getQuery();
        return $query->getResult();
    }
}
