# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    person_repository_service:
        class: AppBundle\Repository\PersonRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: [ AppBundle\Entity\Person]